#!/usr/bin/env sh

# RUNDIR=`dirname $0`
# PIDFILE="${RUNDIR}/$0.pid"
PIDFILE="/tmp/$0.pid"
 
if [ -s ${PIDFILE} ]; then
   SPID=`cat ${PIDFILE}`
   if [ -e /proc/${SPID}/status ]; then
      exit 0
  fi
  cat /dev/null > ${PIDFILE}
fi
echo $$ > ${PIDFILE}

while sleep 360; do
    if [[ -n "$(netstat | grep ":ssh " |  grep ESTABLISHED)" ]]; then
        http_code=$(curl -I -H "Devshell-Vm-Ip-Address:${DEVSHELL_IP_ADDRESS}" -X POST -s -w %{http_code} -o /dev/null ${DEVSHELL_SERVER_URL}/devshell/vmheartbeat);
    fi
done
